### PR TITLE
include iojs-v3 in travis ci build

### PR DESCRIPTION
**Pull request by growlsworth**
Hey @marcominetti, I'm not sure if the build passes in iojs-v3. Thought I'd have travis check it out in a PR.

### CODE REVIEW

**Comment by marcominetti** [comment]
Ok, I'll have a look tomorrow. Does it build or not? The iojs 3 changes v8 so maybe a fix is needed...

**Comment by growlsworth** [comment]
I attempted to update my app to iojs-3.0.0 today and I don't believe it builds. Thanks for taking a look. This is an incredibly useful tool.

**Comment by marcominetti** [comment]
I've almost done, but seems the new v8 does not triggers GC on requests. I've opened an issue at https://github.com/nodejs/node/issues/2478

**Comment by growlsworth** [comment]
Awesome. Thanks for looking into it.

**Comment by marcominetti** [comment]
The new memwatch compiles but v8 stucks on (memwatch).gc() call in iojs 3.x... In previous iojs/nodejs versions gc works fine.

**Comment by growlsworth** [comment]
Thanks for the merge. Helpful in knowing what works/doesn't in 3.0.0.

**Pull request merged**
